image: Visual Studio 2019

environment:
  matrix:
  - solution_name: Semester-4/Homework-3/LambdaInterpreter/LambdaInterpreter.sln

before_build:
  - dotnet restore %solution_name%

build_script:
  - dotnet build %solution_name%

test_script:
  - dotnet test %solution_name%