image: Visual Studio 2017

environment:
  matrix:
  - solution_path: Semester-2\Test-Final\Sem2FinalTest\Sem2FinalTest.sln
  
before_build:
  - nuget restore %solution_path%

build:
   project: %solution_path%

test_script:
  - nunit3-console %solution_path% \
    --result=myresults.xml;format=AppVeyor