image: Visual Studio 2017

before_build:
  - nuget restore Semester-2\Test-Final\Sem2FinalTest\Sem2FinalTest.sln

build:
   project: Semester-2\Test-Final\Sem2FinalTest\Sem2FinalTest.sln

test_script:
  - nunit3-console Semester-2\Test-Final\Sem2FinalTest\Sem2FinalTest.sln \
    --result=myresults.xml;format=AppVeyor