image: Visual Studio 2019

environment:
  matrix:
  - solution_name: Semester-4/Test/Task1/Task1/Task1.sln
  - solution_name: Semester-4/Test/Task2/Task2/Task2.sln
  - solution_name: Semester-4/Test/Task3/Task3/Task3.sln
  - solution_name: Semester-4/Homework-1/Factorial/Factorial/Factorial.sln
  - solution_name: Semester-4/Homework-1/Fibonacci/Fibonacci/Fibonacci.sln
  - solution_name: Semester-4/Homework-1/FirstInList/FirstInList/FirstInList.sln
  - solution_name: Semester-4/Homework-1/ListReverse/ListReverse/ListReverse.sln
  - solution_name: Semester-4/Homework-1/PowerList/PowerList/PowerList.sln

before_build:
  - dotnet restore %solution_name%

build_script:
  - dotnet build %solution_name%

test_script:
  - dotnet test %solution_name%