image: Visual Studio 2017

before_build:
  - nuget restore Semester-2/Homework-7/WinFormsCalculator/WinFormsCalculator.sln

build:
   project: Semester-2/Homework-7/WinFormsCalculator/WinFormsCalculator.sln

test_script:
  - nunit3-console Semester-2/Homework-7/WinFormsCalculator/WinFormsCalculator.sln \
    --result=myresults.xml;format=AppVeyor