image: Visual Studio 2017

before_build:
  - nuget restore Semester-2/Homework-2/HashTable/HashTable.sln

build:
   project: Semester-2/Homework-2/HashTable/HashTable.sln

test_script:
  - nunit3-console Semester-2/Homework-2/HashTable/HashTable.sln \
    --result=myresults.xml;format=AppVeyor