image: Visual Studio 2017

before_build:
  - nuget restore Semester-2/TestGame/TestGame.sln

build:
   project: Semester-2/TestGame/TestGame.sln

test_script:
  - nunit3-console Semester-2/TestGame/TestGame.sln \
    --result=myresults.xml;format=AppVeyor