image: ubuntu

environment:
  matrix: 
  - solution_name: Semester-3/Homework-1/LazyCalculation.sln
  - solution_name: Semester-3/Homework-3/MyThreadPool.sln

build_script:
  - dotnet build %solution_name%

test_script:
  - dotnet test %solution_name%