image: Visual Studio 2019

before_build:
  - dotnet restore Semester-3/Homework-5/SimpleFTP.sln

build:
  project: Semester-3/Homework-5/SimpleFTP.sln

test_script:
  - dotnet test Semester-3/Homework-5/SimpleFTP.sln
