image: Visual Studio 2017

before_build:
  - nuget restore Semester-2/Homework-4/ParseTree/ParseTree.sln

build:
   project: Semester-2/Homework-4/ParseTree/ParseTree.sln

test_script:
  - nunit3-console Semester-2/Homework-4/ParseTree/ParseTree.sln \
    --result=myresults.xml;format=AppVeyor