image: Visual Studio 2017

before_build:
  - nuget restore Semester-2/Homework-6/MapFilterFoldFunctions/MapFilterFoldFunctions.sln

build:
   project: Semester-2/Homework-6/MapFilterFoldFunctions/MapFilterFoldFunctions.sln

test_script:
  - nunit3-console Semester-2/Homework-6/MapFilterFoldFunctions/MapFilterFoldFunctions.sln \
    --result=myresults.xml;format=AppVeyor