image: Visual Studio 2017

before_build:
  - nuget restore Semester-2/Test-1/Test-1.sln

build:
   project: Semester-2/Test-1/Test-1.sln

test_script:
  - nunit3-console Semester-2/Test-1/Test-1.sln \
    --result=myresults.xml;format=AppVeyor